### ISSUE TITLE
Unable to authenticate with private Github repo - fails build every time

### ISSUE THREAD

**Issue by joeandaverde** [groupon/DotCi#103]
The Github client is prompting for username when trying to clone private repo. It fails with:

    [bunch of stuff show in image below]
    Cloning into '/var/myorg/myrepo'...
    fatal: could not read Username for 'https://github.com': No such device or address

I have provided client access key and authorized the application to have access to private repos through OAuth.

Jenkins ver. 1.595

May be related to #102 

![image](https://cloud.githubusercontent.com/assets/696255/5555959/26f890b2-8c8f-11e4-8e1d-cb4ddd231040.png)

**Comment by Dinoshauer** [comment]
Following this, as I would like to use dotCI with our private repos :+1:

**Comment by Dinoshauer** [comment]
Just a correction to @joeandaverde 's temporary solution with a `.git-credential` file it should be named `.git-credentials` :+1: for that!

**Comment by justicel** [comment]
@suryagaddipati I'm stuck on solving for this issue. Just wanted to +1 this as an issue for myself as well.

**Comment by pcorliss** [comment]
Same issue here.

**Comment by vineetbaldwa** [comment]
Same issue here with trying to load a private repo as a git submodule.

**Comment by suryagaddipati** [comment]
Private repos now work in `2.7.1` using `Docker compose build type`
