### ISSUE TITLE
Integrate native support for downstream builds

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi#11]
Currently the only way for DotCi to initiate a downstream build is inconvenient.
It involves remotely trigger via url by passing a bunch of build parameters ...

    Use the following URL to trigger build remotely: 
    JENKINS_URL/job/xxx/build?token=TOKEN_NAME or /buildWithParameters?token=TOKEN_NAME 
    Optionally append &cause=Cause+Text to provide text that will be included in the recorded build cause.

It would be nice if there was a new DotCi syntax for initiating downstream build(s).
This would resolve cases where the code repository does not contain the deployment procedures, browser testing framework, etc.

    build:
      [ before | run | after ]: 
        ...
        <% if( DOTCI_BRANCH =~ /deploy_request*/) { %>
        - downstream:
            deploy_foo:
               wait: true
               params:
                 sha: $SHA
                 branch: $DOTCI_BRANCH 
                 repo: $GIT_URL
                 environment: load_testing
            test_bar:
               wait: false
               params:
                 environment: load_testing
                 service: foo
        <% } %>
        ...  

I'm not sure how the syntax should be structured for sequential downstream builds versus parallel downstream builds.

Also since the above settings imply that not every branch would not invoke a downstream build.
Then its representation should only appear when viewing that build number job. It would be nice to if some downstream build status icon would also appear in the left side bar by that build number.

**Comment by jeffbyrnes** [comment]
:+1: for upstream/downstream build support.

**Comment by vvitayau** [comment]
This feature is now available

```
plugins:
  - downstream_job:
      on_result: 'success'
      <org>/<repo>:
        BRANCH: "master"
        FQDN: "${FQDN}"
```

the only issue is FQDN needs to be a parameter in DotCi configuration for FQDN to be passable

**Comment by jeffbyrnes** [comment]
@vvitayau are there also upstream builds?

**Comment by jeffbyrnes** [comment]
@suryagaddipati I believe I was a bit mislead by one of my teammates on how our projects are built, and was lead to believe that building a project with upstream dependencies would first do a fresh build of said deps (i.e., an upstream build), before building itself.
