### ISSUE TITLE
[DockerBuild] linked containers are not given unique names

### ISSUE THREAD

**Issue by dougjohnson** [groupon/DotCi#116]
```yml
image: my_image
command:
  unit_tests: ./run_unit_tests.sh
  integration_tests: ./run_integration_tests.sh
links:
  - image: mysql
```

The above .ci.yml file should start up two ```mysql``` containers and link the ```unit_tests``` container to one and the ```integration_tests``` container to the other. This is useful as it completely isolates the parallel build steps.

What actually happens is best illustrated by a sample ```docker ps``` while the builds are running:

```
CONTAINER ID   IMAGE       COMMAND               CREATED          STATUS         PORTS       NAMES
85e60e99adad   my_image    ./run_unit_tests.sh   8 seconds ago    Up 7 seconds               naughty_torvalds
e7919ece3067   my_image    ./run_integration_t   8 seconds ago    Up 7 seconds               prickly_sammet
795bcbe20d27   mysql       mysqld_safe --log-bi  9 seconds ago    Up 8 seconds   3306/tcp    mysql_54d3b0ffe4b0159ae2f3bf912015-02-06_13-43-40,naughty_torvalds/mysql,prickly_sammet/mysql
8da9d4fbfc65   mysql       mysqld_safe --log-bi  9 seconds ago    Up 8 seconds   3306/tcp
```

The cause seems to be that both parallel builds attempt to run a ```mysql``` container but both **give it the same name**. Perhaps because the docker daemon received the requests at almost the same time, the second request does not fail and the second container is created without a name.

When cleaning up, the ```mysql``` container with no name is not removed and remains on the host as an orphaned container.

Also, if one of the parallel builds fails, it kills the ```mysql``` container, hosing the other builds that are dependent on it.

The fix seems to be to **ensure that linked containers are always given unique names.**

**Comment by suryagaddipati** [comment]
@dougjohnson we have deprecated this style of build over `docker compose build`s.  
https://github.com/groupon/DotCi/blob/master/docs/DockerBuild.md 

That should fix this issue ?
