### ISSUE TITLE
Github hook expecting JSON output

### ISSUE THREAD

**Issue by justicel** [groupon/DotCi#121]
Howdy all. I'm having an issue with getting the github hook portion of the plugin to work. I get the following error: http://pastebin.com/1kNZZuqH 

From the error it looks like perhaps it's trying to use JSON data from github, while github is being set to use form encoded data perhaps?

**Comment by suryagaddipati** [comment]
@justicel thats weird. Do you get the same error if you flip the payload type manually in github webhook ?

**Comment by justicel** [comment]
@suryagaddipati Let me try. One second.

**Comment by justicel** [comment]
@suryagaddipati Okay, apparently actually this might be due to the first request that github is sending when the webhook is created. I generated a pull request and it did not result in a 500 error. I can post a sanitized version of the payload if that will be helpful, but I think you can easily replicate this by making a new DotCI job from a repository and then looking at the failed payload in the github webhooks.

**Comment by suryagaddipati** [comment]
@justicel  oh right. that makes sense. There should be code to ignore ping requests from github and not cause an error. 

Thanks for bringing this up.

**Comment by justicel** [comment]
@suryagaddipati Okay, great. Now I have a new issue. Any of the groupon devs happen to be in the jenkins IRC channel? :)

**Comment by suryagaddipati** [comment]
@justicel i usually hangout there once in a while but not consistently. Not there ATM. 

What issue are you encountering ?

**Comment by justicel** [comment]
Oh. Apparently this one. Just went through the open issue list: https://github.com/groupon/DotCi/issues/109

**Comment by suryagaddipati** [comment]
@justicel oh I didn't get a chance to investigate that one yet. Its on my backlog.

**Comment by justicel** [comment]
Downgrading to 1.596 for now as well. Thanks again!

**Comment by suryagaddipati** [comment]
Sure thing. Let me know if you run into anymore issues.

**Comment by suryagaddipati** [comment]
@gblikegroupon do you know if we figured out what was causing this issue in later jenkins ?
