### ISSUE TITLE
Git commit URL link uses the "/api/v3" prefix, which fails to open the commit URL

### ISSUE THREAD

**Issue by marcellodesales** [groupon/DotCi#140]
Hi guys,

The commit link to the associated build, displayed in the top of the build page with the GitHub logo icon, is pointing to the commit SHA URL with the `/api/v3` appended to it. 

<img width="1430" alt="screen shot 2015-07-11 at 10 46 50 am" src="https://cloud.githubusercontent.com/assets/131457/8634774/32013398-27bb-11e5-9527-c62a4f5cd364.png">

* http://github.intuit.com/api/v3/repos/mdesales/isp/commit/49d730adb048e1697cdea994791144e0eb670ca0

Instead of

* http://github.intuit.com/mdesales/isp/commit/49d730adb048e1697cdea994791144e0eb670ca0

That way, it does not take the user to the appropriate commit page. Instead, it shows the API error...

```js
{
message: "Must authenticate to access this API.",
documentation_url: "https://developer.github.com/v3"
}
```

thanks!
Marcello

**Comment by suryagaddipati** [comment]
fixed on master

**Comment by marcellodesales** [comment]
@suryagaddipati thanks for the fix!
