### ISSUE TITLE
mvn:run through docker seems to be missing static assets

### ISSUE THREAD

**Issue by ppg** [groupon/DotCi#146]
I'm trying to run dotci so I can make some changes/contributions but I don't want to have to install maven on my dev machine so I am trying to do it via docker. I can get it up and running and most things work, but when I try to go to dotci specific stuff it can't find any of the assets. Some examples of missing asset urls:
http://localhost:8080/jenkins/static/cd31ed2d/plugin/DotCi/bower_components/paper-input/paper-input.html
http://localhost:8080/jenkins/static/cd31ed2d/plugin/DotCi/bower_components/paper-item/paper-item.html

I'm guessing I'm missing some build step, but I can't seem to find it in the README. Also, if there's a better place to ask this than an issue on the repository, please point me that direction.

To reproduce with docker you can run:
```
# Optional: avoids redownloading maven cache all the time
docker create --name maven-data -v ~/.m2:/root/.m2:rw -v ~/.ivy2:/root/.ivy2:rw ubuntu
docker run --name jenkins-mongo -d mongo
docker run --volumes-from maven-data --link jenkins-mongo -v $(pwd):/code -w /code -p 8080:8080 maven mvn hpi:run
```
And just make sure you configure the mongo host as `jenkins-mongo`.

**Comment by ppg** [comment]
FYI, I think I found the answer to this; there's a step to run `npm run build` that compiles all these items.

**Comment by ppg** [comment]
I did have a follow on for this though; I'm trying to make a plugin that is going to add some new build types, but when I bring that one up with docker (very similar to the linked PR) I get issues with finding the same static files; shouldn't the fact that I have dotci as a dependency in my pom.xml pull in a fully functional plugin, static assets and all?

**Comment by suryagaddipati** [comment]
> I get issues with finding the same static files;  

assets should be at `${resURL}/plugin/DotCi/<asset-name>` 
`resURL` is the unique id that jenkins generates for each plugin that can be queried via plugin manager.
