### ISSUE TITLE
Overriding docker-compose command doesn't work with entrypoint style images

### ISSUE THREAD

**Issue by Lykathia** [groupon/DotCi#153]
By always having the shell command inlined, DotCI encounters errors with [entrypoint](https://docs.docker.com/reference/builder/) in exec form.

>Command line arguments to docker run <image> will be appended after all elements in an exec form ENTRYPOINT, and will override all elements specified using CMD. This allows arguments to be passed to the entry point, i.e., docker run <image> -d will pass the -d argument to the entry point. You can override the ENTRYPOINT instruction using the docker run --entrypoint flag.

https://github.com/groupon/DotCi/blob/master/src/main/java/com/groupon/jenkins/buildtype/dockercompose/BuildConfiguration.java#L81

Example
---

**.ci.yml**
```
run:
  example: "test"
```

**docker-compose.yml**
```
example:
  image: pitchplay/scala-dev
  command: "~run"
```

**docker image:** https://github.com/pitchplay/docker-scala-dev/blob/master/Dockerfile#L25

Output
---
```
docker-compose -f docker-compose.yml -p example01 run -T example sh -xc 'test'
...
[info] Set current project to example (in build file:/root/app/)
[error] Not a valid command: sh
[error] Expected 'show'
[error] Not a valid project ID: sh
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: sh
[error] sh
[error]   ^
```

**Comment by suryagaddipati** [comment]
fixed in `2.20.0`
