### ISSUE TITLE
If session is lost on job details page it spins forever

### ISSUE THREAD

**Issue by ppg** [groupon/DotCi#154]
If you're logged out of Jenkins while you're on a job details page, perhaps looking at a run, and then you click somewhere else the AJAXy UI allows you to go there, but then the spinner shows forever since you're forbidden access. The JS should probably detect a 403 response and redirect to the login page (with the current page remembered too as a bonus).

There's possibly other failure cases on the spinner too, would be nice to get a generic error handler that at least stops the spinner and says something is wrong, so there's some sort of UI feedback.

**Comment by suryagaddipati** [comment]
Thanks for reporting this issue. 

Fixed on master. Should go out on next release.
