### ISSUE TITLE
fatal: could not read Username for 'https://github.enterprise.com': No such device or address

### ISSUE THREAD

**Issue by marcellodesales** [groupon/DotCi#170]
Hi there,

I'm creating a new install of DotCI on a host with the latest Jenkins connected to GitHub Enterprise... All in their latest versions... Our GitHub Enterprise also requires authenticated connections over HTTPS. I'm also behind an HTTP_PROXY.

Failure Attempting to Build
--------

The failure to build is as follows:

```
fatal: could not read Username for 'https://github.enterprise.com': No such device or address
```

Is there anything I'm missing? I'm following the instructions from http://groupon.github.io/DotCi/installation/index.html

<img width="1288" alt="screen shot 2015-10-06 at 3 39 22 pm" src="https://cloud.githubusercontent.com/assets/131457/10324755/efb96e04-6c40-11e5-9bfc-b9693df93fca.png">

Commit STATUS API going to wrong PROTOCOL
-----

One point also to make is that the API call to the STATUS is calling `http` instead of `https` on `setting commit status on Github for http://github.intuit.com/api/v3/repos/mdesales/isp/commit/49d730adb048e1697cdea9`. I haven't used `http` anywhere in my settings.

```
Build step 'Execute shell' marked build as failure
setting commit status on Github for http://github.intuit.com/api/v3/repos/mdesales/isp/commit/49d730adb048e1697cdea994791144e0eb670ca0
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

Jenkins Settings
-------

<img width="1016" alt="screen shot 2015-10-06 at 3 39 58 pm" src="https://cloud.githubusercontent.com/assets/131457/10324757/fb273640-6c40-11e5-9483-dd3dce4dbd8b.png">

GitHub Settings
-----

<img width="744" alt="screen shot 2015-10-06 at 3 47 03 pm" src="https://cloud.githubusercontent.com/assets/131457/10324824/8a371684-6c41-11e5-8265-f248863f7f3f.png">

**Comment by suryagaddipati** [comment]
@vvitayau would you know anything about this?

**Comment by suryagaddipati** [comment]
@marcellodesales i would recommend hiding the urls and oauth app keys in the screenshots for security.

**Comment by vvitayau** [comment]
@marcellodesales are you using [DotCi-2.12.3](https://updates.jenkins-ci.org/download/plugins/DotCi/2.12.3/DotCi.hpi)

Also I highly recommend setup from the repo mentioned by the last line of [PreRequisites](http://groupon.github.io/DotCi/installation/PreRequisites.html)

@suryagaddipati you'll note that I don't specify http anywhere in https://github.com/groupon/DotCi/pull/142/files

**Comment by marcellodesales** [comment]
Hi @suryagaddipati 

No worries and thanks for the note... Those are a private github enterprise and Jenkins instance... :)

@vvitayau yes, that's the latest version...

<img width="1105" alt="screen shot 2015-10-13 at 12 46 46 am" src="https://cloud.githubusercontent.com/assets/131457/10448794/1ff91468-7144-11e5-95e8-d8d9b0a56372.png">

**Comment by suryagaddipati** [comment]
hey @marcellodesales I am unclear on how to fix this. Do you have any suggestions?

I am closing this issue for now. Feel free to reopen it if you think anything can be done to fix this.
