### ISSUE TITLE
Docker Compose builds are leaking containers in one case

### ISSUE THREAD

**Issue by srlochen** [groupon/DotCi#172]
We've seen one case where a Docker compose build was leaking containers that were not cleaned up after the builds finished. These containers continued to hang around, and overtime accumulated so much that they choked the build host for resources.

In the one case we saw, the job orchestrated a numbed of containers with Docker Compose, but only one container stuck around. In this case it appeared that the build was trying to kill the container but was  using the wrong string for the container name. The build showed the following command:

`trap "docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 kill; docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 rm -v --force; exit" PIPE QUIT INT HUP EXIT TERM`

But the host on which it was running had the following container:
`# docker ps
CONTAINER ID        IMAGE                                                                      COMMAND                CREATED             STATUS              PORTS                   NAMES
2fff59259659        cibackbeatbackbeatserver274_ci                                             "bin/run-tests.sh"     4 minutes ago       Up 15 seconds`

Note the difference between `cibackbeatbackbeatserver274 ` and `cibackbeatbackbeatserver274_ci `

We need to close this gap so containers don't hang around indefinitely.

**Comment by vvitayau** [comment]
[src/main/java/com/groupon/jenkins/buildtype/dockercompose/BuildConfiguration.java#L75](https://github.com/groupon/DotCi/commit/3ce5f25b8b4c493ed0b8ca79055261acd1d75138) needs investigation why container was not properly clean up

**Comment by vvitayau** [comment]
wonder if https://github.com/docker/compose/issues/1651 resolves this issue as-of docker-compose >= 1.4.0

**Comment by vvitayau** [comment]
Appears issue is using ``docker-compose run`` instead of ``docker-compose up`` per

```
$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps
                 Name                               Command               State    Ports
------------------------------------------------------------------------------------------
cibackbeatbackbeatserver274_ci_run_1     bin/run-tests.sh                 Up
cibackbeatbackbeatserver274_database_1   /docker-entrypoint.sh postgres   Up      5432/tcp
cibackbeatbackbeatserver274_redis_1      /entrypoint.sh redis-server      Up      6379/tcp

$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 stop
Stopping cibackbeatbackbeatserver274_database_1... done
Stopping cibackbeatbackbeatserver274_redis_1... done

$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps
                 Name                               Command                State     Ports
------------------------------------------------------------------------------------------
cibackbeatbackbeatserver274_ci_run_1     bin/run-tests.sh                 Up
cibackbeatbackbeatserver274_database_1   /docker-entrypoint.sh postgres   Exit 137
cibackbeatbackbeatserver274_redis_1      /entrypoint.sh redis-server      Exit 0

$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 kill

$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps
                 Name                               Command                State     Ports
------------------------------------------------------------------------------------------
cibackbeatbackbeatserver274_ci_run_1     bin/run-tests.sh                 Up
cibackbeatbackbeatserver274_database_1   /docker-entrypoint.sh postgres   Exit 137
cibackbeatbackbeatserver274_redis_1      /entrypoint.sh redis-server      Exit 0
GM28126:backbeat_server victorv

$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 rm -v --force
Going to remove cibackbeatbackbeatserver274_database_1, cibackbeatbackbeatserver274_redis_1
Removing cibackbeatbackbeatserver274_database_1... done
Removing cibackbeatbackbeatserver274_redis_1... done

$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps
                Name                       Command        State   Ports
-----------------------------------------------------------------------
cibackbeatbackbeatserver274_ci_run_1   bin/run-tests.sh   Up
```

**Comment by vvitayau** [comment]
the solution appears to be
```
$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps
                Name                       Command        State   Ports
-----------------------------------------------------------------------
cibackbeatbackbeatserver274_ci_run_1   bin/run-tests.sh   Up

$ docker stop cibackbeatbackbeatserver274_ci_run_1
cibackbeatbackbeatserver274_ci_run_1

$ docker kill cibackbeatbackbeatserver274_ci_run_1

$ docker rm -v --force cibackbeatbackbeatserver274_ci_run_1

$ docker-compose -f docker-compose.yml -p cibackbeatbackbeatserver274 ps
Name   Command   State   Ports
------------------------------
```

**Comment by vvitayau** [comment]
this is a docker-compose issue .... created https://github.com/docker/compose/issues/2184

**Comment by vvitayau** [comment]
Exploring the customize use of [after_each](https://github.com/groupon/DotCi/pull/209) targeted specifically to master to resolve where ``docker-compose [ps | logs | rm]`` does not identify availability of SERVICE after using ``docker-compose run SERVICE``

For example if SERVICE is master then
```
run:
  master:

after_each: 'docker rm -vf `basename \$PWD`__master_run_1'
```

**Comment by vvitayau** [comment]
Going to wait for https://github.com/docker/compose/issues/2593

**Comment by vvitayau** [comment]
Determined that changing trap to ``docker-compose rm --all --force`` will resolve this issue.
