### ISSUE TITLE
Running scripts after scm checkout but before run scripts

### ISSUE THREAD

**Issue by aheuermann** [groupon/DotCi#180]
I am hoping to be able to run a script after checkout, but before the parallel run.  Is this possible currently? If not, would you be open to a PR to add this?

**Comment by suryagaddipati** [comment]
http://groupon.github.io/DotCi/user-guide/DockerCompose/#before 

Would that work?

**Comment by aheuermann** [comment]
I tried using the before, but it looks like it runs for each parallel sub-build.  I was hoping to run a script once before the parallel builds start.

**Comment by suryagaddipati** [comment]
@aheuermann I would like the "conductor" in parallel build to be a "Flyweight" ( meaning it won't consume any executors) eventually . I am not sure it would be a good idea to run shell scripts on the flyweight. 


Curious if you have an example of what you are trying to do.

**Comment by aheuermann** [comment]
We have a rather large set of integration suites that we are wanting to run in parallel. I'm using the before to build the images for the tests and migrating the database. Building these images takes around 10 min right now mostly based on network dependencies (pulling images from docker registry, npm install, ect), but also a database migration and compiling some golang code.  There are some things we will be doing to speed up this setup, but would be nice to build these images once and then reference them in each parallel run by pushing them to a local docker registry or something. This way it is only taking up 1 executor during this "build" phase and also it would guarantee each test is running based on the same set of images.

**Comment by suryagaddipati** [comment]
I see. Thats seems like a common enough pattern, we do something similar  in our other builds using matrix plugin's capstone build . 

How do you think the syntax of   `.ci.yml` should look like ? Perhaps the current `before` should be renamed to `post_checkout` or something ?

**Comment by aheuermann** [comment]
I'm not sure if `post_checkout` would be clear to newcomers.  It wasn't clear to me that the parallel jobs would run on separate executors at first. So I wasn't aware that multiple checkouts would happen (I'm relatively new to jenkins). 

With that in mind, I lean towards something like `before_each` or even `before_each_run` to be very clear (although a little verbose). For the script that is run once, I like `before` or `before_run` (if it has to be different than the current `before`). 

So my `.ci.yml` would something look something like.
```yml
before: "this_script_runs_once.sh"
before_each: "this_runs_before_each_parallel_run.sh"
run:
  node1: "grunt test_1"
  node2: "grunt test_2"
  node3: "grunt test_3"
  golang: "go test -v ./..."
```
Let me know what you think.  I don't have a strong preference, I think it will be clear after reading the yml page in the docs.

**Comment by aheuermann** [comment]
If you are still open to this, I may have some time to take a look at this over the next couple days.  Let me know what you think.

**Comment by suryagaddipati** [comment]
@aheuermann yea I think its a good idea. I've have been out of action past couple of days.
