### ISSUE TITLE
Downstream build plugin does not work

### ISSUE THREAD

**Issue by daniel-beard** [groupon/DotCi#189]
- When building from a pull request, the DOTCI_BRANCH variable is set to something like "Pull Request: 1234"
- You need to pass a `BRANCH` var to the downstream plugin to get it to build.
- Referencing any environment variable that has a `:` in it causes the build to fail.
- Is it a templating engine limitiation? Is there any way to escape the strings properly?

**Comment by vvitayau** [comment]
uncertain if https://github.com/groupon/DotCi/issues/11 is resolved based on this bug
so http://groupon.github.io/DotCi/user-guide/Plugins could use beefing up.

**Comment by aheuermann** [comment]
I noticed that  [`DOTCI_BRANCH` is set to `Pull Request: #` here for pull requests.](https://github.com/groupon/DotCi/blob/master/src/main/java/com/groupon/jenkins/github/Payload.java#L75).  I think that may be what is causing this issue.

**Comment by suryagaddipati** [comment]
Closing this for more user input.
