### ISSUE TITLE
.ci.yml is pulled from source branch for pull requests rather than the "merged" branch

### ISSUE THREAD

**Issue by aheuermann** [groupon/DotCi#196]
It looks like [the issue is here](https://github.com/groupon/DotCi/blob/master/src/main/java/com/groupon/jenkins/buildtype/dockercompose/DockerComposeBuild.java#L92) where `build.sha()` is the sha of the last commit on the source branch and not the "merged sha".  

The github api provides a [`merge_commit_sha`](https://developer.github.com/v3/pulls/#response-1), but it is deprecated. It may be simpler to just move the checkout to the first step in the DockerCompose build.

**Comment by suryagaddipati** [comment]
>It may be simpler to just move the checkout to the first step in the DockerCompose build. 

You mean, do a checkout and read `.ci.yml` from workspace instead of using api?

**Comment by aheuermann** [comment]
yeah

**Comment by suryagaddipati** [comment]
That makes sense. We'd have to co a checkout on the `conductor`, shouldn't be an issue I guess since we run the `conductor` on a full executor. 

On a related not. Looks like it currently doesn't rebuild  PR's from the same repo assuming it was already built. But this behavior is wrong considering we need to test the merged branch.

**Comment by aheuermann** [comment]
Ok, I can look into reading the .ci.yml from the workspace.
 
Are you referring to the `buildPullRequestsFromSameRepo` setting? Should that setting be removed and have builds always run for PRs?

**Comment by suryagaddipati** [comment]
>Are you referring to the buildPullRequestsFromSameRepo setting? Should that setting be removed and have builds always run for PRs?

Yes. Exactly.
