### ISSUE TITLE
Where can I find an example file for a docker/ruby project?

### ISSUE THREAD

**Issue by compwron** [groupon/DotCi#206]
I am trying to get CI working for an existing codebase which does not have a ci build. http://groupon.github.io/DotCi/user-guide/DockerCompose/ has been helpful but I am still getting errors along the lines of "Run language_version=2.1.2 finished with : FAILURE" What should I be reading? 

I think that it would help me if there were more full examples in the guide at http://groupon.github.io/DotCi/user-guide/DockerCompose/

**Comment by suryagaddipati** [comment]
hi @compwron here is a full example of .ci.yml 

http://groupon.github.io/DotCi/user-guide/Examples/#ciyml-example 

>"Run language_version=2.1.2 finished with : FAILURE"  

looks like one of the sub builds failed in this case.

I will try to add more examples to docs.
