### ISSUE TITLE
docker-compose build settings

### ISSUE THREAD

**Issue by ingoclaro** [groupon/DotCi#207]
Hi,

it would be nice if the docker-compose build type would support a similar config than the install-packages build type.
For example the before_run config it's named differently and only supports a string instead of an array.

In summary the ask is to have a config like:

```
build:
  info:
    - env
  before:
    - shell command
  run:
    - docker compose stuff (same as current run section at the root of the config).
  after:
    - shell command
environment:
  vars:
    MY_VAR: hello
```

etc...
just make the config compatible, just keeping the params that make sense for docker compose.

thanks!

**Comment by suryagaddipati** [comment]
supported now
