### ISSUE TITLE
Restrict sub builds to same slave node as master build

### ISSUE THREAD

**Issue by aheuermann** [groupon/DotCi#210]
Are you aware of a way to restrict sub builds to same slave node as master build with dotci? 

From searching, people recommend the node label and parameterized build plugin together; however, I don't think there is a way to specify these parameters for dotci sub builds.

**Comment by suryagaddipati** [comment]
hello @aheuermann . Its theorectically possible if we pass in `LabelAssignmentAction` [here](https://github.com/groupon/DotCi/blob/master/src/main/java/com/groupon/jenkins/dynamic/build/execution/SubBuildScheduler.java#L91)

Curious what your use case is.
