### ISSUE TITLE
NPM installs fail regularly 

### ISSUE THREAD

**Issue by aaarichter** [groupon/DotCi#233]
<img width="1140" alt="bildschirmfoto 2016-03-31 um 14 01 49" src="https://cloud.githubusercontent.com/assets/2707029/14175155/76567090-f749-11e5-82d9-b3c65287dcfc.png">

when DotCi/Push and DotCi/PR are both active, DotCI/Push tends to fail extremely often in the npm install phase.

This is super annoying

**Comment by suryagaddipati** [comment]
This error is not related to this project. What happens inside a build is upto you.

Pls reopen the issue if you think this is directly related to DotCi
