### ISSUE TITLE
When clicking on "Build with Parameters" link, provide drop down of branches

### ISSUE THREAD

**Issue by alexkogon** [groupon/DotCi#26]
It would be nice if the "Build with Parameters" page queried Github for the available branches and displayed them in a drop down or list box to select, instead of having to know the exact name of the branch you want to run and having to type it in

**Comment by alexkogon** [comment]
Did you fix it? LOL

I hear DotCI is integrated with Docker now, if I have a change would like to check that out.

Hope you are well

**Comment by suryagaddipati** [comment]
he @alexkogon yah it is fixed :) 

Whole lot of changes ,
http://groupon.github.io/DotCi/ 

Yea doing well. Hope you are doing well as well.

**Comment by alexkogon** [comment]
Cool.man. Will be in touch soonish
