### ISSUE TITLE
Do not ignore webhooks for tags

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi#32]
Need DotCi to enable webhook for tags to execute builds.
This will offer development the ability to configuring different behaviors for tags like nexus publish releases if a certain naming convention else ignore.

 The first step would be to enable tags by undoing

* https://github.com/groupon/DotCi/blob/7f1b14635fc596da66135234541264fd1fa9d803/src/test/java/com/groupon/jenkins/github/PayloadTest.java#L152-L155
* https://github.com/groupon/DotCi/blob/7f1b14635fc596da66135234541264fd1fa9d803/src/main/java/com/groupon/jenkins/github/Payload.java#L104-#L106

The second step would be to supply a variable to be used that represents that tag.

I also propose an additional third step that involves defining an entire new build section for execution of code when a tag. This is a cleaner way to avoid git tag invocation of a build:run ... and vice-versa.   Otherwise every developer will have to re-modify their existing .ci.yml to distinguish the new behavior support for git tag.

```
build:
  run:
     - ....
  tag:
    <% if (DOTCI_TAG =~ /some_naming_convention-SNAPSHOT/ %>
    - ... nexus publish snapshot
    <% else if (DOTCI_TAG =~ /some_naming_convention/ %>
    - ... nexus publish release
    <% } else { %>
    - skip # ignore some developer tag for their own sanity to mark their code
    <% } %>
```

**Comment by ebenoist** [comment]
I'm going to +1 this. Because I want to only push semantically versioned containers into a docker registry (not unlike tagging wars for nexus), ignoring tags means I can't specifically pivot on that logic to build my production releases. A tag is a git artifact and should be treated like any other. What is the reason for this distinction?

**Comment by vvitayau** [comment]
Tested on staging and will be available as soon as DotCi-2.7.2 is cut per https://github.com/groupon/DotCi/compare/DotCi-2.7.1...master

**Comment by vvitayau** [comment]
https://github.com/groupon/DotCi/compare/DotCi-2.7.1...DotCi-2.7.2
```
node version: v0.12.2
npm Version: 2.7.4
Maven Version: 3.2.5
JDK Version: 1.7.0_75
```

> 
git checkout master
git reset --hard origin/master
git pull
mvn release:clean
npm install
sudo npm install webpack -g
webpack --release=true  --colors --progress  src/main/jsx/app.jsx
mvn -Dresume=false --batch-mode release:prepare
mvn release:perform

**Comment by vvitayau** [comment]
requires __/configure__ your DotCi project to enable 'Build Tags'

* a pushed branch cut refs/heads/abc becomes DOTCI_BRANCH=abc
* a pushed tag refs/tags/def becomes DOTCI_TAG=def
