### ISSUE TITLE
Improve visibility of build log in multi config run

### ISSUE THREAD

**Issue by cybermaak** [groupon/DotCi#4]
When having a multi config run (e.g. .ci.yml with after: section), clicking the the 'Console output' of the Jenkins job shows a DotCI console output vs the build log as in single config run.

To get to the build log, you need to go to status then click the 'default' link, which is not easily discoverable .

#####Suggestion:
In the DotCI console output add direct links to every configs output for easier discoverability.

For example, a typical output looks like this 
```
Started by GitHub push by xxx
[EnvInject] - Loading node environment variables.
Building remotely on xxx workspace xxxxxx
Triggering script=default
script=default appears cancelled: 1
Run script=default finished with : SUCCESS
Triggering script=post_build
Run script=post_build finished with : SUCCESS
setting commit status on Github for xxxxxxxxxxxx
Finished: SUCCESS
```

Clicking on 'script=default' or 'script=post_build' get you to the config's history rather than the output of the config for that run

The suggestion would be to add a link in the output to jump you directly the configs' output for that run

**Comment by suryagaddipati** [comment]
fixed in new UI
