### ISSUE TITLE
by default ...  "Delete workspace before build starts" should be enabled

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi#46]
I can't think of a good reason why "Delete workspace before build starts" should not be enabled.
It will prevent previous build artifacts/report on the master of prior builds 
from being incorporated by the current artifacts/report running on the slave.

Not doing so can lead to false broken builds.
e.g its possible a prior build had generates a broken test report that exists on the master build.

It's rare but development may require previous report to generate differences against the current report. They can disable this field ... rather than forcing all most developments who create new builds to enable this parameter.

**Comment by tmack8001** [comment]
Not having this as a default causes a lot of confusion as any error logs based on workspace files will lead people and developers down the wrong path wondering what is wrong with their build setups.

**Comment by danmconrad** [comment]
I agree this should be a default value.

**Comment by vvitayau** [comment]
DotCi now by default cleans workspace before build per

https://github.com/groupon/DotCi/blame/master/src/main/java/com/groupon/jenkins/buildtype/dockercompose/BuildConfiguration.java#L165
```
 shellCommands.add("chmod -R u+w . ; find . ! -path \"./deploykey_rsa.pub\" ! -path \"./deploykey_rsa\" -delete");
```

**Comment by vvitayau** [comment]
Interesting side note: 

Docker user beware of volume mounting as root. It's recommend that docker-compose.override.yml be setup to create the userid of the slave agent. Because testing can result in creation of files and if image is running as root then those files will now be owned by root. However, the next build will lack permission to to perform the necessary find delete in the subsequent build, as the slave agent userid.
